### ISSUE TITLE
Dockerfile not generating when using `revali build` command

### ISSUE THREAD

**Issue by matthewtsmith** [mrgnhnt96/revali#6]
Hello, I am attempting to deploy my first Revali based server. I have followed your instructions on using the Docker construct to create the Dockerfile.

My pubspec.yaml is as follows:

```yaml
name: ems_server
description: EMS Server API
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  apptree_mobile_admin:
    git:
      url: https://github.com/apptreesoftware/apptreemobile_admin_sdks
      path: apptree_mobile_sdk_dart
  revali_annotations: ^1.3.0
  revali_router: ^2.1.1

dev_dependencies:
  revali: ^1.4.1
  revali_server: ^1.12.1
```

My understanding is that the revali_server construct should automatically cause the Dockefile to be generated.

I then used `dart run revali build` to generate the server but I do not see a Dockerfile within the .revali folder. 

I have included a screenshot of my .revali folder so you can view the contents being generated.

<img width="338" alt="Image" src="https://github.com/user-attachments/assets/f57ae1f9-3e19-4135-8339-e558feb3d4bd" />

I have also tried creating a `revali.yaml` file to ensure that revali_docker is enabled.

revali.yaml
```
constructs:
  - name: revali_docker
    package: revali_server
    enabled: true
```
